// AI-generated by Claude Sonnet 4.6 via Claude Code
// Integration tests for Koa REST API.
// Requires --experimental-sqlite (Node 22+) for the SQLite layer.
//
// LLM strategy: global fetch is replaced with a mock before the routes are
// imported.  Requests that target the test server itself are passed through to
// the real fetch; everything else (Ollama calls) receives a canned JSON
// response that satisfies all three pipeline artifact types.

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { getDb } from '../server/db/drafts.js';

// Must be set before api.js is loaded so JobPackService picks the right adapter
process.env.LLM_BACKEND = 'ollama-local';

// A single response string that works for all three artifact types:
//   resume / coverLetter → stored as plain text (parseResponse returns rawText)
//   infographic          → the JSON object inside is extracted by parseResponse
const MOCK_LLM_RESPONSE =
  '{"pros":["Great culture","Remote-friendly"],"cons":["Long hours","High pressure"]}';

const originalFetch = globalThis.fetch;

// Draft IDs created during tests — cleaned up in after()
const testDraftIds = new Set();

let server;
let base; // e.g. "http://localhost:54321"

// ---------------------------------------------------------------------------
// Suite setup / teardown
// ---------------------------------------------------------------------------

before(async () => {
  // Dynamic imports run after process.env is set, ensuring the adapter
  // selected by JobPackService is OllamaLocalAdapter (uses fetch internally).
  const [{ default: Koa }, { koaBody }, { default: router }] = await Promise.all([
    import('koa'),
    import('koa-body'),
    import('../server/routes/api.js'),
  ]);

  const app = new Koa();
  app.use(koaBody());
  app.use(router.routes());
  app.use(router.allowedMethods());

  await new Promise((resolve) => {
    server = http.createServer(app.callback());
    server.listen(0, resolve); // port 0 → OS picks a free port
  });

  const { port } = server.address();
  base = `http://localhost:${port}`;

  // Intercept fetch:
  //   - Requests to our test server → forward to real network
  //   - Everything else (Ollama) → return mock LLM response
  globalThis.fetch = async (url, init) => {
    if (url.startsWith(base)) {
      return originalFetch(url, init);
    }
    return {
      ok: true,
      json: async () => ({ response: MOCK_LLM_RESPONSE }),
    };
  };
});

after(async () => {
  globalThis.fetch = originalFetch;

  // Delete only the drafts this test suite created
  const db = getDb();
  const del = db.prepare('DELETE FROM drafts WHERE id = ?');
  for (const id of testDraftIds) {
    del.run(id);
  }

  await new Promise((resolve) => server.close(resolve));
});

// ---------------------------------------------------------------------------
// POST /api/generate
// ---------------------------------------------------------------------------

describe('POST /api/generate', () => {
  it('returns 200 and a numeric draftId for valid inputs', async () => {
    const res = await fetch(`${base}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        jobDescription: 'Senior Node.js Engineer at Acme Corp',
        candidateProfile: 'Jane Doe — 5 years Node.js, TypeScript',
      }),
    });
    assert.equal(res.status, 200);
    const body = await res.json();
    assert.equal(typeof body.draftId, 'number', 'draftId should be a number');
    testDraftIds.add(body.draftId);
  });

  it('returns 400 when jobDescription is omitted', async () => {
    const res = await fetch(`${base}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ candidateProfile: 'Jane Doe' }),
    });
    assert.equal(res.status, 400);
    const body = await res.json();
    assert.ok(body.error, 'response should include an error message');
  });

  it('returns 400 when candidateProfile is omitted', async () => {
    const res = await fetch(`${base}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ jobDescription: 'Some job' }),
    });
    assert.equal(res.status, 400);
  });

  it('returns 400 when the body is empty', async () => {
    const res = await fetch(`${base}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({}),
    });
    assert.equal(res.status, 400);
  });
});

// ---------------------------------------------------------------------------
// GET /api/drafts
// ---------------------------------------------------------------------------

describe('GET /api/drafts', () => {
  it('returns 200 and a JSON array', async () => {
    const res = await fetch(`${base}/api/drafts`);
    assert.equal(res.status, 200);
    const body = await res.json();
    assert.ok(Array.isArray(body));
  });

  it('each entry contains id, label, job_key, created_at, updated_at', async () => {
    // Seed a draft so the list is definitely non-empty
    const genRes = await fetch(`${base}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        jobDescription: 'Product designer at StartupXYZ',
        candidateProfile: 'Alex — 3 years UI/UX',
      }),
    });
    const { draftId } = await genRes.json();
    testDraftIds.add(draftId);

    const res = await fetch(`${base}/api/drafts`);
    const drafts = await res.json();
    assert.ok(drafts.length > 0, 'list should have at least one draft');

    const seeded = drafts.find((d) => d.id === draftId);
    assert.ok(seeded, 'newly created draft must appear in the list');
    for (const field of ['id', 'label', 'job_key', 'created_at', 'updated_at']) {
      assert.ok(field in seeded, `draft should have a '${field}' field`);
    }
  });
});

// ---------------------------------------------------------------------------
// GET /api/drafts/:id
// ---------------------------------------------------------------------------

describe('GET /api/drafts/:id', () => {
  let draftId;

  before(async () => {
    const res = await fetch(`${base}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        jobDescription: 'Backend engineer at WidgetCo',
        candidateProfile: 'Sam — Go and Node.js developer',
      }),
    });
    const body = await res.json();
    draftId = body.draftId;
    testDraftIds.add(draftId);
  });

  it('returns the draft with all artifact fields populated', async () => {
    const res = await fetch(`${base}/api/drafts/${draftId}`);
    assert.equal(res.status, 200);
    const draft = await res.json();
    assert.equal(draft.id, draftId);
    assert.ok(draft.job_description, 'job_description should be present');
    assert.ok(draft.candidate_profile, 'candidate_profile should be present');
    assert.ok(draft.resume_text, 'resume_text should be populated after generation');
    assert.ok(draft.cover_letter_text, 'cover_letter_text should be populated');
    assert.ok(draft.infographic_data, 'infographic_data should be populated');
  });

  it('returns 404 for an id that does not exist', async () => {
    const res = await fetch(`${base}/api/drafts/999999`);
    assert.equal(res.status, 404);
  });
});

// ---------------------------------------------------------------------------
// GET /api/drafts/compare
// ---------------------------------------------------------------------------

describe('GET /api/drafts/compare', () => {
  let id1, id2;

  before(async () => {
    const [r1, r2] = await Promise.all([
      fetch(`${base}/api/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ jobDescription: 'Job A at CompanyA', candidateProfile: 'Profile A' }),
      }),
      fetch(`${base}/api/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ jobDescription: 'Job B at CompanyB', candidateProfile: 'Profile B' }),
      }),
    ]);

    id1 = (await r1.json()).draftId;
    id2 = (await r2.json()).draftId;
    testDraftIds.add(id1);
    testDraftIds.add(id2);
  });

  it('returns 200 with both drafts side by side', async () => {
    const res = await fetch(`${base}/api/drafts/compare?ids=${id1},${id2}`);
    assert.equal(res.status, 200);
    const body = await res.json();
    assert.ok(Array.isArray(body.drafts), 'body.drafts should be an array');
    assert.equal(body.drafts.length, 2);
    const returnedIds = body.drafts.map((d) => d.id);
    assert.ok(returnedIds.includes(id1), 'first draft id should be in response');
    assert.ok(returnedIds.includes(id2), 'second draft id should be in response');
  });

  it('returns 400 when the ids param is missing', async () => {
    const res = await fetch(`${base}/api/drafts/compare`);
    assert.equal(res.status, 400);
  });

  it('returns 400 when fewer than two ids are supplied', async () => {
    const res = await fetch(`${base}/api/drafts/compare?ids=${id1}`);
    assert.equal(res.status, 400);
  });

  it('returns 404 when one of the ids does not exist', async () => {
    const res = await fetch(`${base}/api/drafts/compare?ids=${id1},999999`);
    assert.equal(res.status, 404);
  });
});
