// AI-generated by Claude Sonnet 4.6 via Claude Code
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { generateResumePDF } from '../server/generators/resumePDF.js';
import { generateCoverLetterPDF } from '../server/generators/coverLetterPDF.js';
import { generateInfographic } from '../server/generators/infographic.js';

const SAMPLE_RESUME = [
  '# Jane Doe',
  '## Summary',
  'Backend engineer with 5 years of Node.js experience.',
  '## Experience',
  '### Senior Engineer — Acme Corp (2021–present)',
  '- Built APIs serving 10M requests/day',
  '- Led team of four engineers',
  '## Skills',
  '**Languages**: JavaScript, TypeScript',
  '---',
  '## Education',
  'B.S. Computer Science — State University, 2019',
].join('\n');

const SAMPLE_LETTER = [
  'Dear Hiring Manager,',
  '',
  'I am excited to apply for the Senior Engineer position.',
  '',
  '**Key achievement**: Reduced latency by 40%.',
  '',
  'Sincerely,',
  'Jane Doe',
].join('\n');

// ---------------------------------------------------------------------------
// generateResumePDF
// ---------------------------------------------------------------------------

describe('generateResumePDF', () => {
  it('returns a Buffer', async () => {
    const buf = await generateResumePDF(SAMPLE_RESUME);
    assert.ok(buf instanceof Buffer);
  });

  it('output starts with PDF magic bytes %PDF', async () => {
    const buf = await generateResumePDF(SAMPLE_RESUME);
    assert.equal(buf.slice(0, 4).toString(), '%PDF');
  });

  it('produces a non-trivially-sized output', async () => {
    const buf = await generateResumePDF(SAMPLE_RESUME);
    assert.ok(buf.length > 500, `expected > 500 bytes, got ${buf.length}`);
  });

  it('handles markdown headings and bullet points without throwing', async () => {
    const text = '# Title\n## Section\n- Item one\n- Item two\n### Sub\n**Bold** text';
    const buf = await generateResumePDF(text);
    assert.equal(buf.slice(0, 4).toString(), '%PDF');
  });

  it('handles a horizontal rule line', async () => {
    const buf = await generateResumePDF('Header\n---\nBody');
    assert.equal(buf.slice(0, 4).toString(), '%PDF');
  });

  it('handles minimal single-line input', async () => {
    const buf = await generateResumePDF('Jane Doe');
    assert.equal(buf.slice(0, 4).toString(), '%PDF');
  });
});

// ---------------------------------------------------------------------------
// generateCoverLetterPDF
// ---------------------------------------------------------------------------

describe('generateCoverLetterPDF', () => {
  it('returns a Buffer', async () => {
    const buf = await generateCoverLetterPDF(SAMPLE_LETTER);
    assert.ok(buf instanceof Buffer);
  });

  it('output starts with PDF magic bytes %PDF', async () => {
    const buf = await generateCoverLetterPDF(SAMPLE_LETTER);
    assert.equal(buf.slice(0, 4).toString(), '%PDF');
  });

  it('produces a non-trivially-sized output', async () => {
    const buf = await generateCoverLetterPDF(SAMPLE_LETTER);
    assert.ok(buf.length > 500, `expected > 500 bytes, got ${buf.length}`);
  });

  it('renders inline bold spans without throwing', async () => {
    const buf = await generateCoverLetterPDF('Dear Manager,\n\n**Skills**: Node.js, Python');
    assert.equal(buf.slice(0, 4).toString(), '%PDF');
  });

  it('handles a horizontal rule line', async () => {
    const buf = await generateCoverLetterPDF('Opening\n---\nClosing');
    assert.equal(buf.slice(0, 4).toString(), '%PDF');
  });
});

// ---------------------------------------------------------------------------
// generateInfographic
// ---------------------------------------------------------------------------

describe('generateInfographic', () => {
  it('returns a string', () => {
    const svg = generateInfographic({ pros: ['Good culture'], cons: ['Long hours'] });
    assert.equal(typeof svg, 'string');
  });

  it('starts with an XML declaration', () => {
    const svg = generateInfographic({ pros: ['Good culture'], cons: ['Long hours'] });
    assert.ok(svg.startsWith('<?xml'), 'expected <?xml declaration');
  });

  it('contains an <svg> element', () => {
    const svg = generateInfographic({ pros: ['Good culture'], cons: ['Long hours'] });
    assert.ok(svg.includes('<svg '));
  });

  it('includes pros and cons text in the output', () => {
    const svg = generateInfographic({
      pros: ['Remote work', 'Strong benefits'],
      cons: ['Long hours', 'High pressure'],
    });
    assert.ok(svg.includes('Remote work'));
    assert.ok(svg.includes('Long hours'));
    assert.ok(svg.includes('Pros'));
    assert.ok(svg.includes('Cons'));
  });

  it('escapes XML special characters', () => {
    const svg = generateInfographic({
      pros: ['Salary > $100k'],
      cons: ['Uses <legacy> code & old tools'],
    });
    assert.ok(!svg.includes('</legacy>'), 'unescaped < should not appear');
    assert.ok(svg.includes('&lt;'), 'expected &lt; escape');
    assert.ok(svg.includes('&amp;'), 'expected &amp; escape');
  });

  it('handles empty arrays without throwing', () => {
    assert.doesNotThrow(() => generateInfographic({ pros: [], cons: [] }));
    const svg = generateInfographic({ pros: [], cons: [] });
    assert.ok(svg.includes('<svg '));
  });

  it('defaults missing keys to empty arrays', () => {
    assert.doesNotThrow(() => generateInfographic({}));
    const svg = generateInfographic({});
    assert.ok(svg.includes('<svg '));
  });

  it('word-wraps long text without throwing', () => {
    const longPro = 'This is a very long pro statement that should be wrapped across multiple lines in the SVG output';
    const svg = generateInfographic({ pros: [longPro], cons: [] });
    assert.ok(svg.includes('<svg '));
  });
});
