// AI-generated by Claude Sonnet 4.5 via Claude Code — scaffolded from CLAUDE.md and sprint requirements
import Router from 'koa-router';
import { JobPackService } from '../services/JobPackService.js';
import { getDraft, listDrafts, saveDraftEdits } from '../db/drafts.js';
import { generateResumePDF } from '../generators/resumePDF.js';
import { generateCoverLetterPDF } from '../generators/coverLetterPDF.js';
import { generateInfographic } from '../generators/infographic.js';

const router = new Router({ prefix: '/api' });
const service = new JobPackService();

// POST /api/generate — kick off generation, returns draft ID
router.post('/generate', async (ctx) => {
  const { jobDescription, candidateProfile } = ctx.request.body;
  if (!jobDescription || !candidateProfile) {
    ctx.status = 400;
    ctx.body = { error: 'jobDescription and candidateProfile are required' };
    return;
  }
  const { draftId } = await service.generateJobPack(jobDescription, candidateProfile);
  ctx.body = { draftId };
});

// GET /api/drafts — list all drafts
router.get('/drafts', async (ctx) => {
  ctx.body = listDrafts();
});

// GET /api/drafts/compare?ids=id1,id2 — return two drafts side by side
// Must be registered before /drafts/:id so "compare" is not captured as a param.
router.get('/drafts/compare', async (ctx) => {
  const idsParam = ctx.query.ids;
  if (!idsParam) {
    ctx.status = 400;
    ctx.body = { error: 'ids query param required (e.g. ?ids=1,2)' };
    return;
  }
  const ids = idsParam.split(',').map(Number).filter(n => Number.isInteger(n) && n > 0);
  if (ids.length !== 2) {
    ctx.status = 400;
    ctx.body = { error: 'Exactly two numeric ids required' };
    return;
  }
  const drafts = ids.map(id => getDraft(id));
  if (drafts.some(d => !d)) {
    ctx.status = 404;
    ctx.body = { error: 'One or more drafts not found' };
    return;
  }
  ctx.body = { drafts };
});

// GET /api/drafts/:id — get one draft
router.get('/drafts/:id', async (ctx) => {
  const draft = getDraft(Number(ctx.params.id));
  if (!draft) { ctx.status = 404; ctx.body = { error: 'Not found' }; return; }
  ctx.body = draft;
});

// POST /api/drafts/:id/save — save edits
router.post('/drafts/:id/save', async (ctx) => {
  const { label, resumeText, coverLetterText } = ctx.request.body;
  saveDraftEdits(Number(ctx.params.id), { label, resumeText, coverLetterText });
  ctx.body = { ok: true };
});

// GET /api/drafts/:id/resume.pdf
router.get('/drafts/:id/resume.pdf', async (ctx) => {
  const draft = getDraft(Number(ctx.params.id));
  if (!draft?.resume_text) { ctx.status = 404; ctx.body = 'Not found'; return; }
  const pdf = await generateResumePDF(draft.resume_text);
  ctx.set('Content-Type', 'application/pdf');
  ctx.set('Content-Disposition', `attachment; filename="resume-${draft.id}.pdf"`);
  ctx.body = pdf;
});

// GET /api/drafts/:id/coverletter.pdf
router.get('/drafts/:id/coverletter.pdf', async (ctx) => {
  const draft = getDraft(Number(ctx.params.id));
  if (!draft?.cover_letter_text) { ctx.status = 404; ctx.body = 'Not found'; return; }
  const pdf = await generateCoverLetterPDF(draft.cover_letter_text);
  ctx.set('Content-Type', 'application/pdf');
  ctx.set('Content-Disposition', `attachment; filename="coverletter-${draft.id}.pdf"`);
  ctx.body = pdf;
});

// GET /api/drafts/:id/infographic.svg
router.get('/drafts/:id/infographic.svg', async (ctx) => {
  const draft = getDraft(Number(ctx.params.id));
  if (!draft?.infographic_data) { ctx.status = 404; ctx.body = 'Not found'; return; }
  const data = JSON.parse(draft.infographic_data);
  const svg = generateInfographic(data);
  ctx.set('Content-Type', 'image/svg+xml');
  ctx.body = svg;
});

export default router;
