// AI-generated by Claude Sonnet 4.5 via Claude Code — scaffolded from CLAUDE.md and sprint requirements
// Strategy interface — all concrete adapters must implement generate(prompt)
export class LLMBackend {
  async generate(prompt) {
    throw new Error('generate(prompt) must be implemented by concrete adapter');
  }
}
